# Generated by Django 4.2.13 on 2024-06-01 11:02

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('student', '0002_alter_category_category'),
    ]

    operations = [
        migrations.CreateModel(
            name='MasterActivity',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('Type', models.CharField(max_length=255)),
                ('Subject', models.CharField(max_length=255)),
                ('Comment', models.CharField(max_length=500)),
                ('IsDeleted', models.BooleanField(default=False)),
                ('AssignedUser', models.TextField(max_length=255)),
                ('CreatedBy', models.TextField(max_length=255)),
                ('CreatedDate', models.DateField(auto_now_add=True)),
                ('ModifiedBy', models.TextField(max_length=255)),
                ('ModifiedDate', models.DateField(auto_now=True)),
                ('ActivityType', models.TextField(max_length=255)),
            ],
        ),
    ]
