# Generated by Django 4.2.13 on 2024-06-01 11:07

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('student', '0003_masteractivity'),
    ]

    operations = [
        migrations.AlterField(
            model_name='masteractivity',
            name='ActivityType',
            field=models.CharField(max_length=255),
        ),
        migrations.AlterField(
            model_name='masteractivity',
            name='AssignedUser',
            field=models.CharField(max_length=255),
        ),
        migrations.AlterField(
            model_name='masteractivity',
            name='Comment',
            field=models.TextField(max_length=500),
        ),
        migrations.AlterField(
            model_name='masteractivity',
            name='CreatedBy',
            field=models.CharField(max_length=255),
        ),
        migrations.AlterField(
            model_name='masteractivity',
            name='ModifiedBy',
            field=models.CharField(max_length=255, null=True),
        ),
    ]
