# Generated by Django 4.2.13 on 2024-06-01 14:59

from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('student', '0004_alter_masteractivity_activitytype_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='masteractivity',
            name='DueDate',
            field=models.DateField(default=django.utils.timezone.now),
            preserve_default=False,
        ),
    ]
