# Generated by Django 4.2.13 on 2024-06-01 15:31

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('student', '0005_masteractivity_duedate'),
    ]

    operations = [
        migrations.CreateModel(
            name='MemberDetails',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('MemberID', models.CharField(max_length=255)),
                ('MemberName', models.CharField(max_length=255)),
                ('MemberPhone', models.CharField(max_length=255)),
                ('MemberEmail', models.CharField(max_length=255)),
                ('MemberAddress', models.CharField(max_length=255)),
                ('MemberType', models.CharField(max_length=255)),
            ],
        ),
    ]
