# Generated by Django 4.2.13 on 2024-06-07 15:25

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('student', '0006_memberdetails'),
    ]

    operations = [
        migrations.AddField(
            model_name='memberdetails',
            name='profile_picture',
            field=models.ImageField(blank=True, null=True, upload_to='profile_pics/'),
        ),
    ]
