# Generated by Django 4.2.13 on 2024-06-07 15:46

from django.db import migrations, models
import uuid


class Migration(migrations.Migration):

    dependencies = [
        ('student', '0007_memberdetails_profile_picture'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='memberdetails',
            name='id',
        ),
        migrations.AddField(
            model_name='memberdetails',
            name='MemberUUID',
            field=models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False, unique=True),
        ),
    ]
