# Generated by Django 4.2.13 on 2024-06-08 13:01

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('student', '0008_remove_memberdetails_id_memberdetails_memberuuid'),
    ]

    operations = [
        migrations.AddField(
            model_name='memberdetails',
            name='MemberScore',
            field=models.DecimalField(decimal_places=2, default=1, max_digits=6),
            preserve_default=False,
        ),
    ]
