# Generated by Django 4.2.13 on 2024-06-10 08:24

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('student', '0009_memberdetails_memberscore'),
    ]

    operations = [
        migrations.CreateModel(
            name='Loan',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('LoanType', models.CharField(max_length=255)),
                ('LoanPassingOfficer', models.CharField(max_length=255)),
                ('LoanAmount', models.DecimalField(decimal_places=3, max_digits=100)),
                ('LoanTenure', models.DecimalField(decimal_places=2, max_digits=4)),
                ('InterestRate', models.DecimalField(decimal_places=2, max_digits=5)),
                ('AmountRepayed', models.DecimalField(decimal_places=2, max_digits=100)),
                ('Member', models.CharField(max_length=50)),
            ],
        ),
        migrations.CreateModel(
            name='Offer',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('Name', models.CharField(max_length=255)),
                ('percentage', models.DecimalField(decimal_places=2, max_digits=4)),
                ('Bonus', models.DecimalField(decimal_places=2, max_digits=4)),
                ('ExpiryDate', models.DateField()),
                ('FromDate', models.DateField(auto_now_add=True)),
                ('ToDate', models.DateField()),
                ('Member', models.CharField(max_length=50)),
            ],
        ),
    ]
